<?php 
/************************************************************************/
/* AChecker                                                             */
/************************************************************************/
/* Copyright (c) 2008 - 2018                                            */
/* Inclusive Design Institute                                           */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
/* This file was generated by the AChecker 1.5 installation script.     */
/* File generated 2026-05-01 11:05:37                                   */
/************************************************************************/
/************************************************************************/
/* the database user name                                               */
define('DB_USER',                      'root');

/* the database password                                                */
define('DB_PASSWORD',                  '');

/* the database host                                                    */
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      'achecker');

/* Database type: mysql or sqlite */
define('DB_TYPE',                      'sqlite');

/* Path to SQLite database file (only used if DB_TYPE is 'sqlite') */
define('SQLITE_PATH',                  dirname(__FILE__) . '/../database/achecker.db');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: AC_                                                 */
define('TABLE_PREFIX',                 'AC_');

/* Where the temporary files are located.  This includes all file       */
/* manager and imported files.  If security is a concern, it is         */
/* recommended that the temporary directory be moved outside of the web	*/
/* accessible area.														*/
$temp_path = realpath(dirname(__FILE__) . '/../temp/');
if (!$temp_path || !is_writable($temp_path)) {
    $sys_temp = sys_get_temp_dir();
    // Try to create a specific subdirectory in system temp to avoid collisions
    $achecker_temp = $sys_temp . DIRECTORY_SEPARATOR . 'achecker_temp';
    if (!is_dir($achecker_temp)) {
        @mkdir($achecker_temp, 0755, true);
    }
    
    // If we can write to the achecker_temp, use it; otherwise fallback to sys_temp itself
    if (is_writable($achecker_temp)) {
        $temp_path = $achecker_temp;
    } else {
        $temp_path = $sys_temp;
    }
}
define('AC_TEMP_DIR', rtrim($temp_path, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR);

/* DO NOT ALTER THIS LAST LINE                                          */
define('AC_INSTALL', TRUE);

/* Enable debugging mode to see failing check code in logs */
define('AC_DEBUG', TRUE);

?>
